name: 'Upload Results'
description: 'Common upload result step'
runs:
  using: "composite"
  steps:
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
        name: test-results-${{ github.job }}
        path: ./**/build/reports/
