site_name: App Platform
site_url: https://amzn.github.io/app-platform/
repo_name: app-platform
repo_url: https://github.com/amzn/app-platform
edit_uri: edit/main/docs/
site_description: "A lightweight application framework for state and memory management suitable for Kotlin Multiplatform projects."
remote_branch: gh-pages
copyright: 'Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.'

# https://squidfunk.github.io/mkdocs-material/
theme:
  name: 'material'
  favicon: images/favicon.png
  logo: images/logo.svg
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: blue grey
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: blue grey
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: 'Inter'
    code: 'Fira Code'

  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tooltips
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.follow
    - toc.integrate
    - content.tabs.link
    - content.action.edit

  icon:
    edit: material/pencil

markdown_extensions:
  - smarty
  - codehilite:
      guess_lang: false
  - footnotes
  - def_list
  - meta
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - tables
  - admonition
  - attr_list
  - md_in_html

nav:
  - 'Introduction': index.md
  - 'Setup': setup.md
  - 'Module Structure': module-structure.md
  - 'Scope': scope.md
  - 'Presenter': presenter.md
  - 'Renderer': renderer.md
  - 'Template': template.md
  - 'DI Framework': di.md
  - 'Testing': testing.md
  - 'FAQ': faq.md
  - 'Changelog': changelog.md

plugins:
  - search
  - social:
      cards_layout_options:
        logo: docs/images/app-platform-logo.png
