

package software.amazon.app.platform.metro.compiler.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link software.amazon.app.platform.metro.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class FirDiagnosticTestGenerated extends AbstractFirDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesrenderer")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesrenderer {
    @Test
    public void testAllFilesPresentInContributesrenderer() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesrenderer"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("missingInjectOnNonZeroArgConstructor.kt")
    public void testMissingInjectOnNonZeroArgConstructor() {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesrenderer/missingInjectOnNonZeroArgConstructor.kt");
    }

    @Test
    @TestMetadata("modelTypeMustBeExplicitWhenNotInferable.kt")
    public void testModelTypeMustBeExplicitWhenNotInferable() {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesrenderer/modelTypeMustBeExplicitWhenNotInferable.kt");
    }

    @Test
    @TestMetadata("redundantInjectOnZeroArgConstructor.kt")
    public void testRedundantInjectOnZeroArgConstructor() {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesrenderer/redundantInjectOnZeroArgConstructor.kt");
    }

    @Test
    @TestMetadata("rendererMustNotBeSingleton.kt")
    public void testRendererMustNotBeSingleton() {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesrenderer/rendererMustNotBeSingleton.kt");
    }
  }

  @Nested
  @TestMetadata("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesrobot")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesrobot {
    @Test
    public void testAllFilesPresentInContributesrobot() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesrobot"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("classMustImplementRobot.kt")
    public void testClassMustImplementRobot() {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesrobot/classMustImplementRobot.kt");
    }

    @Test
    @TestMetadata("classWithConstructorParametersMustUseInject.kt")
    public void testClassWithConstructorParametersMustUseInject() {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesrobot/classWithConstructorParametersMustUseInject.kt");
    }

    @Test
    @TestMetadata("onlyAppScopeSupported.kt")
    public void testOnlyAppScopeSupported() {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesrobot/onlyAppScopeSupported.kt");
    }

    @Test
    @TestMetadata("robotMustNotBeSingleton.kt")
    public void testRobotMustNotBeSingleton() {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesrobot/robotMustNotBeSingleton.kt");
    }
  }

  @Nested
  @TestMetadata("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesscoped")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesscoped {
    @Test
    public void testAllFilesPresentInContributesscoped() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesscoped"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("multipleOtherSupertypes.kt")
    public void testMultipleOtherSupertypes() {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesscoped/multipleOtherSupertypes.kt");
    }

    @Test
    @TestMetadata("mustBeInject.kt")
    public void testMustBeInject() {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesscoped/mustBeInject.kt");
    }

    @Test
    @TestMetadata("mustImplementScoped.kt")
    public void testMustImplementScoped() {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesscoped/mustImplementScoped.kt");
    }

    @Test
    @TestMetadata("noSupertypes.kt")
    public void testNoSupertypes() {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesscoped/noSupertypes.kt");
    }

    @Test
    @TestMetadata("useContributesScopedInsteadOfContributesBinding.kt")
    public void testUseContributesScopedInsteadOfContributesBinding() {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/diagnostics/contributesscoped/useContributesScopedInsteadOfContributesBinding.kt");
    }
  }
}
