

package software.amazon.app.platform.metro.compiler.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link software.amazon.app.platform.metro.compiler.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/dump")
@TestDataPath("$PROJECT_ROOT")
public class FirDumpTestGenerated extends AbstractFirDumpTest {
  @Test
  public void testAllFilesPresentInDump() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/dump"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/dump/contributesrobot")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesrobot {
    @Test
    public void testAllFilesPresentInContributesrobot() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/dump/contributesrobot"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("defaultConstructorRobot.kt")
    public void testDefaultConstructorRobot() {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/dump/contributesrobot/defaultConstructorRobot.kt");
    }

    @Test
    @TestMetadata("defaultConstructorRobotIr.kt")
    public void testDefaultConstructorRobotIr() {
      runTest("metro-extensions/contribute/impl-compiler-plugin/src/test/resources/dump/contributesrobot/defaultConstructorRobotIr.kt");
    }
  }
}
