name: 'Prepare Emulator'
description: 'Common emulator setup steps'
runs:
  using: "composite"
  steps:
    # This is needed for hardware acceleration, see https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/
    - name: Enable Hardware Acceleration
      shell: bash
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm

    # This is needed to accept the Android license, see https://issuetracker.google.com/issues/193118030
    - name: Accept Android SDK License
      uses: android-actions/setup-android@v3
