name: CI

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:

jobs:
  test-android:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4

      - name: Test
        run: ./gradlew testDebugUnitTest --stacktrace --show-version --continue

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-results-${{ github.job }}
          path: ./**/build/reports/tests/

  test-ios:
    runs-on: macos-latest-xlarge
    timeout-minutes: 25

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4

      - name: Test
        run: ./gradlew iosSimulatorArm64Test -Pkotlin.incremental.native=true --stacktrace --show-version --continue

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-results-${{ github.job }}
          path: ./**/build/reports/tests/

  test-desktop:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4

      - name: Test
        run: ./gradlew desktopTest --stacktrace --show-version --continue

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-results-${{ github.job }}
          path: ./**/build/reports/tests/

  test-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4

      - name: Test
        run: ./gradlew linuxX64Test --stacktrace --show-version --continue

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-results-${{ github.job }}
          path: ./**/build/reports/tests/

  test-jvm-modules:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4

      - name: Test
        run: ./gradlew :kotlin-inject-extensions:contribute:impl-code-generators:test --stacktrace --show-version --continue

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-results-${{ github.job }}
          path: ./**/build/reports/tests/

  test-emulator-renderer-android-view:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4

      # This is needed for hardware acceleration, see https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      # This is needed to accept the Android license, see https://issuetracker.google.com/issues/193118030
      - uses: android-actions/setup-android@v3

      - name: Test
        run: ./gradlew :renderer-android-view:public:emulatorCheck --stacktrace --show-version --continue

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-results-${{ github.job }}
          path: ./**/build/reports/androidTests/

  test-emulator-renderer-compose-multiplatform:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4

      # This is needed for hardware acceleration, see https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      # This is needed to accept the Android license, see https://issuetracker.google.com/issues/193118030
      - uses: android-actions/setup-android@v3

      - name: Test
        run: ./gradlew :renderer-compose-multiplatform:public:emulatorCheck --stacktrace --show-version --continue

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-results-${{ github.job }}
          path: ./**/build/reports/androidTests/

  test-emulator-sample-app:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4

      # This is needed for hardware acceleration, see https://github.blog/changelog/2023-02-23-hardware-accelerated-android-virtualization-on-actions-windows-and-linux-larger-hosted-runners/
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      # This is needed to accept the Android license, see https://issuetracker.google.com/issues/193118030
      - uses: android-actions/setup-android@v3

      - name: Test
        run: ./gradlew :sample:app:emulatorCheck --stacktrace --show-version --continue

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-results-${{ github.job }}
          path: ./**/build/reports/androidTests/

  binary-compatibility-check:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v4

      - name: API check
        run: ./gradlew apiCheck --stacktrace --show-version --continue

  ktfmt:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v4

      - name: ktfmt
        run: ./gradlew ktfmtCheck --stacktrace --show-version --continue

  android-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v4

      - name: Android Lint
        run: ./gradlew lint --stacktrace --show-version --continue

      - name: Upload Android Lint Results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: lint-results-${{ github.job }}
          path: ./**/build/reports/lint-results.html

  detekt:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v4

      - name: Detekt
        run: ./gradlew detekt --stacktrace --show-version --continue

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-results-${{ github.job }}
          path: ./**/build/reports/detekt/detekt.html

  publish-maven-local:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - uses: gradle/actions/setup-gradle@v4

      - name: Publish to Maven Local
        run: |
          ./gradlew publishToMavenLocal --stacktrace --show-version --no-configuration-cache
          ./gradlew -p gradle-plugin publishToMavenLocal --stacktrace --show-version --no-configuration-cache

  build-src:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4

      - name: Run release task
        run: ./gradlew -p buildSrc release --stacktrace --show-version --continue

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-results-${{ github.job }}
          path: ./**/build/reports/tests/

  gradle-plugin:
    runs-on: ubuntu-latest
    timeout-minutes: 25

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4

      - name: Run release task
        run: ./gradlew -p gradle-plugin release --stacktrace --show-version --continue

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        if: ${{ failure() }}
        with:
          name: test-results-${{ github.job }}
          path: ./**/build/reports/tests/
