# Simple workflow for deploying static content to GitHub Pages
name: Deploy Wiki

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:

  # Allows to run this workflow manually from the Actions tab.
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-mkdocs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: |
          cp CHANGELOG.md docs/changelog.md
      - run: |
          pip install mkdocs-material
          pip install "mkdocs-material[imaging]"

      - name: Build docs preview
        if: github.ref != 'refs/heads/main'  # Only runs in PRs
        run: mkdocs build --config-file mkdocs.yml -d test-site
      - name: Upload site
        uses: actions/upload-artifact@v4
        if: github.ref != 'refs/heads/main'  # Only runs in PRs
        with:
          name: site-${{ github.job }}
          path: ./test-site/

      - name: Build docs
        if: github.ref == 'refs/heads/main'  # Only runs on main branch
        run: mkdocs gh-deploy --config-file mkdocs.yml --force
